# SPK multiple-machine Makefile with explicit file list

SHELL = /bin/sh

# Definitions

ROOT =	spk
EXE =	$(ROOT)_$@

SRC =	app.cpp app_cpm.cpp app_lattice.cpp app_lwrf.cpp app_off_lattice.cpp cluster.cpp comm_lattice.cpp comm_off_lattice.cpp create_box.cpp create_sites.cpp diag.cpp diag_array.cpp diag_cluster.cpp diag_energy.cpp diag_propensity.cpp domain.cpp dump.cpp dump_image.cpp dump_text.cpp error.cpp finish.cpp groups.cpp hash.cpp input.cpp lattice.cpp library.cpp main.cpp math_extra.cpp memory.cpp output.cpp pair.cpp pair_lj_cut.cpp potential.cpp random_mars.cpp random_park.cpp read_sites.cpp region.cpp region_block.cpp region_cylinder.cpp region_intersect.cpp region_sphere.cpp region_union.cpp set.cpp shell.cpp solve.cpp solve_group.cpp solve_linear.cpp solve_tree.cpp spparks.cpp timer.cpp universe.cpp variable.cpp app_vacancy.cpp 

INC =	app.h app_cpm.h app_lattice.h app_lwrf.h app_off_lattice.hcluster.h comm_lattice.h comm_off_lattice.h create_box.h create_sites.h diag.h diag_array.h diag_cluster.h diag_energy.h diag_propensity.h domain.h dump.h dump_image.h dump_text.h error.h finish.h groups.h hash.h input.h lattice.h library.h math_extra.h memory.h output.h pair.h pair_lj_cut.h pointers.h potential.h random_mars.h random_park.h read_sites.h region.h region_block.h region_cylinder.h region_intersect.h region_sphere.h region_union.h set.h shell.h solve.h solve_group.h solve_linear.h solve_tree.h spktype.h spparks.h style_app.h style_command.h style_diag.h style_dump.h style_pair.h style_region.h style_solve.h timer.h universe.h variable.h version.h app_vacancy.h 

OBJ = 	$(SRC:.cpp=.o)

# Targets

help:
	@echo 'Type "make target" where target is one of:'
	@echo ''
	@files="`ls MAKE/Makefile.*`"; \
	for file in $$files; do head -1 $$file; done

clean:
	rm -r Obj_*

.DEFAULT:
	@test -f MAKE/Makefile.$@
	@if [ ! -d Obj_$@ ]; then mkdir Obj_$@; fi
	@cp -p $(SRC) $(INC) Obj_$@
	@cp MAKE/Makefile.$@ Obj_$@/Makefile
	@cd Obj_$@; \
	$(MAKE)  "OBJ = $(OBJ)" "INC = $(INC)" "EXE = ../$(EXE)" ../$(EXE)
	@if [ -d Obj_$@ ]; then cd Obj_$@; rm $(SRC) $(INC) Makefile*; fi
